import { SavedPattern } from '../types';
import { generateId } from './utils';

export const SEED_PATTERNS: SavedPattern[] = [
  {
    id: generateId(),
    label: 'Email',
    description: 'Matches a standard email address',
    pattern: '\\b[\\w.+-]+@[\\w-]+\\.[\\w.]+\\b',
    flags: 'gi',
    createdAt: Date.now(),
    lastUsed: Date.now(),
  },
  {
    id: generateId(),
    label: 'URL',
    description: 'Matches HTTP/HTTPS URLs',
    pattern: 'https?:\\/\\/[^\\s/$.?#][^\\s]*',
    flags: 'gi',
    createdAt: Date.now(),
    lastUsed: Date.now(),
  },
  {
    id: generateId(),
    label: 'ISO Date',
    description: 'Matches dates in YYYY-MM-DD format',
    pattern: '\\d{4}-(?:0[1-9]|1[0-2])-(?:0[1-9]|[12]\\d|3[01])',
    flags: 'g',
    createdAt: Date.now(),
    lastUsed: Date.now(),
  },
  {
    id: generateId(),
    label: 'Hex Color',
    description: 'Matches hex color codes',
    pattern: '#(?:[0-9a-fA-F]{3}){1,2}\\b',
    flags: 'gi',
    createdAt: Date.now(),
    lastUsed: Date.now(),
  },
  {
    id: generateId(),
    label: 'IPv4',
    description: 'Matches IPv4 addresses',
    pattern: '\\b(?:\\d{1,3}\\.){3}\\d{1,3}\\b',
    flags: 'g',
    createdAt: Date.now(),
    lastUsed: Date.now(),
  },
  {
    id: generateId(),
    label: 'Phone',
    description: 'Matches phone numbers with optional country code',
    pattern: '\\+?[\\d\\s().\\-]{7,20}',
    flags: 'g',
    createdAt: Date.now(),
    lastUsed: Date.now(),
  },
  {
    id: generateId(),
    label: 'HTML Tag',
    description: 'Matches opening and closing HTML tags',
    pattern: '<\\/?[a-z][a-z0-9]*(?:\\s[^>]*)?>',
    flags: 'gi',
    createdAt: Date.now(),
    lastUsed: Date.now(),
  },
  {
    id: generateId(),
    label: 'Semver',
    description: 'Matches semantic versioning numbers',
    pattern: '\\bv?\\d+\\.\\d+\\.\\d+(?:-[\\w.]+)?\\b',
    flags: 'gi',
    createdAt: Date.now(),
    lastUsed: Date.now(),
  },
  {
    id: generateId(),
    label: 'Credit Card',
    description: 'Matches 16-digit credit card numbers',
    pattern: '\\b(?:\\d{4}[\\s-]?){3}\\d{4}\\b',
    flags: 'g',
    createdAt: Date.now(),
    lastUsed: Date.now(),
  },
  {
    id: generateId(),
    label: 'UUID',
    description: 'Matches UUIDs',
    pattern: '[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}',
    flags: 'gi',
    createdAt: Date.now(),
    lastUsed: Date.now(),
  }
];
